Construction/urls.py
# from django.contrib import admin
# from django.urls import path,include

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',include('construct.urls'))
# ]
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('construct.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

construct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.urls import path,include
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from construct import views as  views 
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from . import login_views, views,client_views,architect_views,engineer_views

urlpatterns = [
     path('',views.homepage),
     path('home/',client_views.admin_home,name='client_home'),
     path('addproject/',client_views.addproject,name='addproject'),
     path("send_architect_notification/", client_views.send_architect_notification,
         name='send_architect_notification'),
     path("admin_notify_architect", client_views.admin_notify_architect,
         name='admin_notify_architect'),

     path("send_engineer_notification/", client_views.send_engineer_notification,
         name='send_engineer_notification'),
     path("admin_notify_engineer", client_views.admin_notify_engineer,
         name='admin_notify_engineer'),

     path('viewprojects',client_views.client_viewprojects,name="client_viewprojects"),
     path('deleteproject',client_views.deleteproject,name='deleteproject'),
     path('editproject/<int:id>',client_views.updateproject),
     path('updateprojectdetails/<int:id>',client_views.updateprojectdetails),
     path("architect/view/feedback/", client_views.architect_task_message,
         name="architect_task_message",),
     path("engineer/view/feedback/", client_views.engineer_task_message,
         name="engineer_task_message",),



     path("login", login_views.login_page, name='login_page'),
     path("architectlogin", login_views.architect_login_page, name='architect_login_page'),
     path("engineerlogin", login_views.engineer_login_page, name='engineer_login_page'),
     path("doLogin/", login_views.doLogin, name='user_login'),
     path("architectdoLogin/", login_views.architectdoLogin, name='architect_user_login'),
     path("engineerdoLogin/", login_views.engineerdoLogin, name='engineer_user_login'),
     path("architect_register",login_views.architect_register,name="architect_register"),
     path("engineer_signup",login_views.engineer_signup,name='engineer_signup'),
     path("logout_user/", login_views.logout_user, name='user_logout'),
     path("check_email_availability", login_views.check_email_availability,
         name="check_email_availability"),



    ###architect
     path('architect_home',architect_views.architect_home,name="architect_home"),
     path("architect/fcmtoken/", architect_views.architect_fcmtoken,
         name='architect_fcmtoken'),
     path("architect/view/notification/", architect_views.architect_view_notification,
         name="architect_view_notification"),
     path("architect/task/", architect_views.architect_task,
         name='architect_task'),
     path("architect/project/", architect_views.architect_project,
         name='architect_project'),
     path("architect/details/", architect_views.architect_details,
         name='architect_details'),
     path("architect/view/profile/", architect_views.architect_view_profile,
         name='architect_view_profile'),



    ###engineer
     path('engineer_home',engineer_views.engineer_home,name="engineer_home"),
     path("engineer/task/", engineer_views.engineer_task,
         name='engineer_task'),
     path("engineer/project/", engineer_views.engineer_project,
         name='engineer_project'),
     path("engineer/view/profile/", engineer_views.engineer_view_profile,
         name='engineer_view_profile'),
     path("engineer/fcmtoken/", engineer_views.engineer_fcmtoken,
         name='engineer_fcmtoken'),
     path("engineer/view/notification/", engineer_views.engineer_view_notification,
         name="engineer_view_notification")




]

construct/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
# from django.db import models
from django.contrib.gis.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser




class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    USER_TYPE = ((1, "CLIENT"), (2, "ARCHITECT"), (3, "ENGINEER"))
    GENDER = [("M", "Male"), ("F", "Female")]
    
    
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    gender = models.CharField(max_length=1, choices=GENDER)
    profile_pic = models.ImageField()
    address = models.TextField()
    fcm_token = models.TextField(default="")  # For firebase notifications
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + ", " + self.first_name

phases = (
	('Site clearing','Site clearing'),
	('Foundation','Foundation'),
	('Plinth beam/slab','Plinth beam/slab'),
	('Superstructure','Superstructure'),
	('Brick masonry work','Brick masonry work'),
	('The lintel','The lintel'),
	('Roofing coating','Roofing coating'),
	('Electrical/plumbing','Electrical/plumbing'),
	('Exterior/interior finishing','Exterior/interior finishing'),
	('Flooring','Flooring'),
	('Painting','Painting')
	)

status=(
		('Complete','Complete'),
		('Incomplete','Incomplete'),
		('Onprogress','Onprogress'),
		('Stopped','Stopped')
		)
project_type = (
	('Fire Resistive','Fire Resistive'),
	('Non-Combustible','Non-Combustible'),
	('Ordinary','Ordinary'),
	('Heavy Timber','Heavy Timber'),
	('Wooden Framed','Wooden Framed')
	)

APPROVALS = (
	('approved','approved'),
	('notapproved','notapproved')
	)
class Architect(models.Model):
    admin =models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20,null=False)
    project_type = models.CharField(max_length=500,choices=project_type,null=True)
    project_plans = models.FileField(upload_to='ArchitectProjectPlans/')
    budget=models.PositiveIntegerField(null=True)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.admin.first_name+" "+self.admin.last_name
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.admin.first_name

class Client(models.Model):
    admin =models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20,null=False)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.admin.email +" "+self.admin.gender
    @property
    def get_instance(self):
        return self
    def __str__(self):
        return self.admin.email      

class Engineer(models.Model):
    admin=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20,null=True,blank=True)
    project_type = models.CharField(max_length=500,choices=project_type,null=True)
    project_images = models.FileField(upload_to='EngineerProjectImages/')
    budget=models.PositiveIntegerField(null=True)
    status=models.BooleanField(default=False)

    @property
    def get_name(self):
        return self.admin.first_name+" "+self.admin.last_name
    @property
    def get_id(self):
        return self.admin.id
    def __str__(self):
        return self.admin.first_name


class BaseContent(models.Model):
	title = models.CharField(max_length=150)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True



class ConstructionProjects(models.Model): 
	project_client = models.ForeignKey(Client,on_delete=models.CASCADE,null=True)
	project = models.CharField(max_length=254)
	descrition = models.CharField(max_length=254)
	project_type = models.CharField(max_length=254, choices=project_type)
	phases = models.CharField(max_length=150,choices=phases)
	project_eng = models.ForeignKey(Engineer,on_delete=models.CASCADE,null=True)
	project_architect = models.ForeignKey(Architect, on_delete=models.CASCADE,null=True)
	project_plans = models.FileField(upload_to='project_plans')
	status = models.CharField(max_length=254,choices=status)
	startdate = models.DateField(null=True,blank=True)
	propdate = models.DateField(null=True,blank=True)

	def __str__(self):
		return self.project



class ArchitectTask(models.Model):
	constructionproject = models.ForeignKey(ConstructionProjects,on_delete=models.CASCADE,null=True)
	archictect_plan = models.FileField(upload_to='ArchitectProjectPlans/')
	progress = models.BigIntegerField(null=True,blank=True)
	status = models.CharField(max_length=254,choices=status)
	reply = models.TextField()
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)   


	

class EngineerTask(models.Model):
	constructionproject = models.ForeignKey(ConstructionProjects,on_delete=models.CASCADE,null=True)
	eng_report = models.FileField(upload_to='engineerReport/')
	eng_images = models.FileField(upload_to='engineerimages/')
	phases = models.CharField(max_length=150,choices=phases)	
	reply = models.TextField()
	eng_approved = models.CharField(max_length=150,choices=APPROVALS,default="notapproved")
    
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)   


class NotificationEngineer(models.Model):
    engineer = models.ForeignKey(Engineer, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackArchitect(models.Model):
    archictect = models.ForeignKey(Architect, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class NotificationArchitect(models.Model):
    archictect = models.ForeignKey(Architect, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackEngineer(models.Model):
    engineer = models.ForeignKey(Engineer, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Client.objects.create(admin=instance)
        if instance.user_type == 2:
            Architect.objects.create(admin=instance)
        if instance.user_type == 3:
            Engineer.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.client.save()
    if instance.user_type == 2:
        instance.architect.save()
    if instance.user_type == 3:
        instance.engineer.save()

construct/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import render,redirect,reverse
from django.db.models import Q
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from  django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.shortcuts import render,redirect,reverse
# from . import forms,models
from django.db.models import Sum
from django.contrib.auth.models import Group
import json
import requests
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                              get_object_or_404, redirect, render)
from django.templatetags.static import static
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import UpdateView

# from .forms import ClientUserForm,ArchitectUserForm,ConstructionProjectForm
from .models import *
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
# Create your views here.


def homepage(request):
	return render(request,'pages/home.html')

# def home(request):
# 	return render(request,'Client/home.html')





	

construct/templates/Client/addproject.html
{% extends "Client/base2.html" %} {% load humanize %} {% block content %}

{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
            	<form  method="post">
            		{% csrf_token %}
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Client Create Project</h3>
                    </div>
                           {% for comp in projects %}
                            <input type="hidden" name="project_client" value="{{comp.id}}">
                            {% endfor %}
                            <div class="row justify-content-between text-left">
				                        <div class="form-group col-sm-6 flex-column d-flex">
				                          <label class="form-control-label px-3">Description:<span class="text-danger"> *</span></label>
				                          <input style="width:900px; height: 150px;margin-left: 20px;" required name="descrition" id="descrition" type="text" multiple class="form-control">
				                        </div>
				                        

				                    </div>
				                    <div class="row justify-content-between text-left">
				                        <div class="form-group col-sm-6 flex-column d-flex">
				                          <label class="form-control-label px-3">Project Name:<span class="text-danger"> *</span></label>
				                          <input style="margin-left: 20px; width:450px" required name="project" id="project" type="project" multiple class="form-control">
				                        </div>
				                        <div class="form-group col-sm-6 flex-column d-flex">
				                          <label class="form-control-label px-3">Project Type:<span class="text-danger"> *</span></label>
				                          <select style="margin-left: -30px !important;" class="form-control" name="project_type" id="project_type" required>
						                            <option>...</option>
						                            <option>Fire Resistive</option>
						                            <option>Non-Combustible</option>
						                            <option>Ordinary</option>
						                            <option>Heavy Timber</option>
						                            <option>Wooden Framed</option>
						                          </select>
				                        </div>
				                    </div>
                    	<div class="row justify-content-end">
                        <div class="form-group col-sm-6">
                          <button type="submit" class="btn-block btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
                 </form>
<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">Available architects</h3>
    </div>
   <div class="tble p-2">

       <table class="tabe table-bordered" style="width:890px !important;font-size: 15px; text-align: center;">
           <tr>
					<th>Architect Name</th>
					<th>Project Type</th>
					<th>Phone No.</th>
					<th style="width:2px !important;">Plans</th>
					<th>Budget</th>
					<th></th>
				</tr>
           {% for architect in sr %}
		        <tr>
		        	<td>{{ architect.admin}}</td>
		        	<td>{{ architect.project_type }}</td>
		        	<td>{{architect.mobile}}</td>
		        	<td>{{ architect.project_plans }}</td>
		        	<td>{{ architect.budget }}</td>
		        	<td><button data-toggle = "modal" data-target = "#myModal"class="btn btn-primary show_notification" value="{{architect.admin.id}}">Send Notification</button> 
                                    </td>
		        	<!-- <td>{{ k.rooms }}</td> -->
		        	<!-- <td>{{ k.mtime }}</td> -->
		        </tr>
		 		{% endfor %}

        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
<div class = "modal fade" id = "myModal" tabindex = "-1" role = "dialog" 
   aria-labelledby = "myModalLabel" aria-hidden = "true">
   
   <div class = "modal-dialog">
      <div class = "modal-content">
         
         <div class = "modal-header">Send Notification
            <button type = "button" class = "close" data-dismiss = "modal" aria-hidden = "true">
                  &times;
            </button>
            
           
         </div>
         
         <div class = "modal-body">
            <div class="form-group">
                <input type="text" id="message" class='form-control'>
                <br>
                <input type="hidden"  id="archictect_id" name="" class='form-control'>
            </div>
         </div>
         
         <div class = "modal-footer">
            <button type = "button" class = "btn btn-danger" data-dismiss = "modal">
               Close
            </button>
            
            <button type = "button" id='send' class = "btn btn-success send_notification">
               Send Notification
            </button>
         </div>
         
      </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
  
</div><!-- /.modal -->
{% endblock content %}
{% block custom_js %}
  <script>
      $(".show_notification").click(function(){
          $("#archictect_id").val($(this).val())
      })
      $(".send_notification").click(function(){
          var id = $("#archictect_id").val()
          var message = $("#message").val()
          sendNotification(id,message);
      })
    function sendNotification(id,message){
        $.ajax({
            url: "{% url 'send_architect_notification' %}",
            type: 'POST',
            data: {
                id: id,
                message:message,
            }
        }).done(function (response) {
           
          if (response == 'True'){
            alert("Notification Sent");
            location.reload();
          }else{
            alert("Notification could not be saved. Please try again.");
          }
           
        }).fail(function (response) {
            alert("Error in saving token")
        })

    }

  </script>
{% endblock custom_js %}

construct/templates/Client/architect_notification.html
{% extends 'Client/base2.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" style="width:700px !important;ma">
                        <h3  class="card-title">{{page_title}}</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>#</th>
                                    <th>Full Name</th>
                                    <th>Email</th>
                                    <th>Gender</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for archictect in allarchictect %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{archictect.last_name}}, {{archictect.first_name}}</td>
                                    <td>{{archictect.email}}</td>
                                    <td>{{archictect.gender}}</td>
                                    <td>
                                        {% if archictect.profile_pic == ""  %}
                                        No Image
                                        {% else %}
                                        <img class="img img-fluid mb-2" height="56" width="56"
                                            src="{{archictect.profile_pic}}" alt="">
                                        {% endif %}
                                    </td>
                                    <td><button data-toggle = "modal" data-target = "#myModal"class="btn btn-primary show_notification" value="{{archictect.id}}">Send Notification</button> 
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class = "modal fade" id = "myModal" tabindex = "-1" role = "dialog" 
   aria-labelledby = "myModalLabel" aria-hidden = "true">
   
   <div class = "modal-dialog">
      <div class = "modal-content">
         
         <div class = "modal-header">Send Notification
            <button type = "button" class = "close" data-dismiss = "modal" aria-hidden = "true">
                  &times;
            </button>
            
           
         </div>
         
         <div class = "modal-body">
            <div class="form-group">
                <input type="text" id="message" class='form-control'>
                <br>
                <input type="hidden"  id="archictect_id" name="" class='form-control'>
            </div>
         </div>
         
         <div class = "modal-footer">
            <button type = "button" class = "btn btn-danger" data-dismiss = "modal">
               Close
            </button>
            
            <button type = "button" id='send' class = "btn btn-success send_notification">
               Send Notification
            </button>
         </div>
         
      </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
  
</div><!-- /.modal -->
{% endblock content %}
{% block custom_js %}
  <script>
      $(".show_notification").click(function(){
          $("#archictect_id").val($(this).val())
      })
      $(".send_notification").click(function(){
          var id = $("#archictect_id").val()
          var message = $("#message").val()
          sendNotification(id,message);
      })
    function sendNotification(id,message){
        $.ajax({
            url: "{% url 'send_architect_notification' %}",
            type: 'POST',
            data: {
                id: id,
                message:message,
            }
        }).done(function (response) {
           
          if (response == 'True'){
            alert("Notification Sent");
            location.reload();
          }else{
            alert("Notification could not be saved. Please try again.");
          }
           
        }).fail(function (response) {
            alert("Error in saving token")
        })

    }

  </script>
{% endblock custom_js %}

construct/templates/Client/project_add.html
project_add.html

construct/templates/Client/updateproject.html
<!-- //templates/edit.html -->
{% extends "Client/base2.html" %}
  {% load widget_tweaks %}
 
<!-- {% block title %}Add New Employee Records{% endblock title %} -->
 
{% block content %}
  <section class="home-section">
    <div class="home-content">
      <!-- <i class='bx bx-menu' ></i> -->
      <!-- <span class="text">Drop Down Sidebar</span> -->
      <div class="col-md-12">
    <!-- <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable</h4>   -->
 <form method="POST" class="post-form" action="/updateprojectdetails/{{project.id}}">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Update project details</h3>  
  </div>  
   </div>  
  <div class="form-group row">  
  <!-- <label class="col-sm-2 col-form-label">Student Id:</label>   -->
  <div class="col-sm-4">  
   <input type="text" style="display:none;" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ project.id }}"/>  
  </div>  
   </div>  
   <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project Name:</label>  
  <div class="col-sm-4">  
   <input type="text" style="height: 40px"  class="form-control" name="project" id="id_project" required maxlength="150" value="{{ project.project }}" />  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project Description:</label>  
  <div class="col-sm-4">  
   <input type="text" style="height: 150px" class="form-control" name="descrition" id="id_descrition" required maxlength="150" value="{{ project.descrition }}" />  
  </div>  
   </div>  
<!--     <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project plan:</label>  
  <div class="col-sm-4">  
   <input type="file" style="height: px" class="form-control" name="project_plans" id="id_project_plans" required maxlength="150" value="{{ project.project_plans }}" />  
  </div>  
   </div>   -->
  <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project Type:</label>  
  <div class="col-sm-4"> 
  <!-- {% render_field form.project_type class="form-control" maxlength="150"%}  -->
   <!-- <input type="text" class="form-control" name="project_type " id="id_project_type " required maxlength="15" value="{{ project.project_type  }}" />   -->
   <select class="form-control" name="project_type" id="id_project_type" value="{{ project.project_type}}" required>
        <option>{{project.project_type}}</option>
        <option>Fire Resistive</option>
        <option>Non-Combustible</option>
        <option>Ordinary</option>
        <option>Heavy Timber</option>
        <option>Wooden Framed</option>

  </select>
  </div>  
   </div> 
  <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project Architect:</label>  
  <div class="col-sm-4">  


    {% render_field form.project_architect class="form-control" maxlength="150"%}

  </div>  
   </div>  
     <div class="form-group row">  
  <label class="col-sm-3 col-form-label">Project Architect:</label>  
  <div class="col-sm-4">  


    {% render_field form.project_eng class="form-control" maxlength="150"%}

  </div>  
   </div>      
  <div class="form-group row">  
  <label class="col-sm-3 col-form-label"></label>  
  <div class="col-sm-4">  
  <button style="width:200px" type="submit" class="btn btn-success btn-lg">Save </button>  
  </div>  
   </div>  
  </div>  
 </form>  
    </div>
  </section>

{% endblock content %}   